services:
  author-service:
    build:
      context: ./AuthorService
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - .env
    networks:
      - blog-network

  blog-discovery:
    build:
      context: ./BlogDiscovery
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - blog-network

  blog-gateway:
    build:
      context: ./BlogGateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - blog-network

  post-service:
    build:
      context: ./PostService
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    env_file:
      - .env
    networks:
      - blog-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - blog-network
    depends_on:
      - author-service
      - post-service

networks:
  blog-network:
    driver: bridge
