global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'author-service'
    metrics_path: '/actuator/prometheus'
    eureka_sd_configs:
      - server: 'http://blog-discovery:8761/eureka'
  
  - job_name: 'post-service'
    metrics_path: '/actuator/prometheus'
    eureka_sd_configs:
      - server: 'http://blog-discovery:8761/eureka'
