spring:
  application:
    name: BlogDiscovery
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sayeedajmal/SayeedBlog
          default-label: main
          search-paths: configs
          clone-on-start: true
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
  server:
    enable-self-preservation: false
