Gateway:
  Cors:
    Url: "*"
    Methods: "GET,POST,PUT,DELETE,OPTION"

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${MicroZone}
      
spring:
  cloud:
    gateway:
      routes:
        - id: AUTHORSERVICE
          uri: lb://AUTHORSERVICE
          predicates:
            - Path=/api/author/**
            - Path=/api/image/**
        - id: POSTSERVICE
          uri: lb://POSTSERVICE
          predicates:
            - Path=/api/post/**
            - Path=/api/comment/**
            - Path=/api/like/**
            - Path=/api/image/**

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    gateway:
      enabled: true
