server:
  port: 8888
  
spring:
  application:
    name: ServerConfig
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sayeedajmal/SayeedBlog
          searchPaths:
            - ServerConfig
          cloneOnStart: true
