# jwt:
#   secret: "asdflsakfjadslkfjdalkdsajfdlskafjdlfkdsajfldskfjdlfkdfjlsadfjaklsfjadslkf"
#   token-validity: 3600
#   refresh-validity: 86400

# database:
#   url: "mongodb+srv://sayeedajmala06:u0gKvef0Ri3P81Dz@cluster0.qadnb.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
#   name: "SayeedBlog"

# cors:
#   url: "*"
#   methods: "GET,POST,PUT,DELETE"

# microservice:
#   zone: "http://blog-discovery:8761/eureka/"

# multipart:
#   enabled: true
#   max-file-size: "10MB"
#   max-request-size: "50MB"

# post:
#   version: "v1.0.0"

JWT_SECRET: "asdflsakfjadslkfjdalkdsajfdlskafjdlfkdsajfldskfjdlfkdfjlsadfjaklsfjadslkf"
JWT_TOKEN_VALIDITY_IN_MILLISECONDS: 3600
JWT_TOKEN_REFRESH_IN_MILLISECONDS: 7200
BlogUrl: "mongodb+srv://sayeedajmala06:u0gKvef0Ri3P81Dz@cluster0.qadnb.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
BlogDB: "SayeedBlog"
APP_VERSION: "1.0.0"
CORS_URL: "*"
CORS_METHODS: "GET, POST, PUT, DELETE"
MicroZone: "http://blog-discovery:8761/eureka/"
MULTIPART_ENABLED: true
MAX_FILE_SIZE: 10485760  # 10 MB
MAX_REQUEST_SIZE: 20971520  # 20 MB
POST_VERSION: "v1"
