jwt:
  secret: "asdflsakfjadslkfjdalkdsajfdlskafjdlfkdsajfldskfjdlfkdfjlsadfjaklsfjadslkf"
  token-validity: 3600
  refresh-validity: 86400

database:
  url: "mongodb+srv://sayeedajmala06:u0gKvef0Ri3P81Dz@cluster0.qadnb.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  name: "SayeedBlog"

cors:
  url: "*"
  methods: "GET,POST,PUT,DELETE"

microservice:
  zone: "http://blog-discovery:8761/eureka/"

multipart:
  enabled: true
  max-file-size: "10MB"
  max-request-size: "50MB"

post:
  version: "v1.0.0"
