server:
  port: 8888

spring:
  application:
    name: ConfigService
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sayeedajmal/ConfigService
          clone-on-start: true